packages:
  - 'packages/*'
catalog:
  '@babel/core': '^7.25.2'
  '@babel/preset-typescript': '^7.24.7'
  '@popperjs/core': '^2.11.8'
  '@rsbuild/core': '1.0.4'
  '@rsbuild/plugin-babel': '1.0.1'
  '@rsbuild/plugin-less': '1.0.1'
  '@rsbuild/plugin-sass': '1.0.1'
  '@rsbuild/plugin-vue': '1.0.1'
  '@rsbuild/plugin-vue-jsx': '1.0.1'
  '@types/fs-extra': '^11.0.4'
  '@types/less': '^3.0.6'
  '@types/lodash': '^4.17.7'
  '@types/markdown-it': '^14.1.2'
  '@types/node': '^20.16.5'
  '@typescript-eslint/eslint-plugin': '^6.21.0'
  '@typescript-eslint/parser': '^6.21.0'
  '@vitejs/plugin-vue': '^5.1.3'
  '@vitejs/plugin-vue-jsx': '^4.0.1'
  '@vitest/coverage-istanbul': '^1.6.0'
  '@vue/babel-plugin-jsx': '^1.2.5'
  '@vue/runtime-core': '^3.5.5'
  '@vue/shared': '^3.5.5'
  '@vue/test-utils': '^2.4.6'
  'autoprefixer': '^10.4.20'
  'commander': '^12.1.0'
  'csstype': '^3.1.3'
  'diffable-html': '^5.0.0'
  'enquirer': '2.4.1'
  'esbuild': '^0.23.1'
  'eslint': '^8.57.0'
  'eslint-config-prettier': '^9.1.0'
  'eslint-plugin-vue': '^9.28.0'
  'fast-glob': '^3.3.2'
  'fs-extra': '^11.2.0'
  'hash-sum': '^2.0.0'
  'highlight.js': '^11.10.0'
  'husky': '^9.1.6'
  'jsdom': '^24.1.3'
  'less': '^4.2.0'
  'lodash': '^4.17.21'
  'markdown-it': '^14.1.0'
  'markdown-it-anchor': '^9.0.1'
  'nano-staged': '^0.8.0'
  'prettier': '^3.3.3'
  'picocolors': '^1.0.1'
  'postcss': '^8.4.47'
  'postcss-load-config': '^6.0.1'
  'rimraf': '^6.0.1'
  'rslog': '^1.2.3'
  'rspack-plugin-virtual-module': '^0.1.13'
  'terser': '^5.31.6'
  'transliteration': '^2.3.5'
  'typescript': '^5.5.4'
  'vite': '^5.4.5'
  'vitest': '^1.6.0'
  'vitest-canvas-mock': '^0.3.3'
  'vue': '^3.5.5'
  'vue-router': '^4.4.5'